version: 2

extras:
  forgot: &keep
      keep-daily: 10
      keep-weekly: 10
      keep-monthly: 10


locations:

  moviepedia-db:
    from: /backup/moviepediafilms.com
    to: bb-db
    hooks:
      before:
        - '/backup_scripts/keep_upto.sh -d /backup/moviepediafilms.com/ -e .gz -k 0'
        - '/backup_scripts/dmysql.sh -s root@moviepediafilms.com -p 3306 -u root -d /backup/moviepediafilms.com/ -c moviepediafilms-db-1 -P <password>'

    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

  nextcloud-db:
    from: /backup/nextcloud
    to: bb-db
    hooks:
      before:
        - '/backup_scripts/keep_upto.sh -d /backup/nextcloud/ -e .gz -k 0'
        - '/backup_scripts/nextcloud.sh -s oci-somnath -n nextcloud-nextcloud-1 -c "maintenance:mode --on"'
        - '/backup_scripts/dpg.sh -s oci-somnath -c nextcloud-db-1 -u nextcloud -d /backup/nextcloud/'
        - '/backup_scripts/nextcloud.sh -s oci-somnath -n nextcloud-nextcloud-1 -c "maintenance:mode --off"'
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

  financehub-db:
    from: /backup/financehub
    to: bb-db
    hooks:
      before:
        - '/backup_scripts/keep_upto.sh -d /backup/financehub/ -e .gz -k 1'
        - '/backup_scripts/ddb.sh -s oci-somnath -c finance-hub-mongo-1 -u root -P <password> -d /backup/financehub/ -t mongo'
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

  nextcloud-html:
    to: bb-data
    from: /backup/nextcloud-html
    hooks:
      before:
        - /backup_scripts/keep_upto.sh -d  /backup/nextcloud-html/ -e .gz -k 0
        - /backup_scripts/nextcloud.sh -s oci-somnath -n nextcloud-nextcloud-1 -c "maintenance:mode --on"
        - /backup_scripts/drd.sh -r oci-somnath -s nextcloud_nextcloud -d /backup/nextcloud-html -p nextcloud-html -v
        - /backup_scripts/nextcloud.sh -s oci-somnath -n nextcloud-nextcloud-1 -c "maintenance:mode --off"
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

  immich-db:
    from: /backup/immich
    to: bb-db
    hooks:
      before:
        - /backup_scripts/keep_upto.sh -d /backup/immich/ -e .gz -k 0
        - /backup_scripts/dpg.sh -s oci-somnath -c immich_postgres -u postgres -d /backup/immich/
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

  immich-data:
    to: bb-data
    from: /mnt/ssd-4tb/immich-data/library
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

  nextcloud-data:
    to: bb-data
    from: /mnt/ssd-4tb/nextcloud-data
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep



  nas-data:
    to: bb-data
    from: /mnt/ssd-4tb/nas-data/common
    cron: '0 0 * * *' # daily
    options:
      forget:
        <<: *keep

backends:
  bb-data:
    type: b2
    path: 'zee-backup:/data'
  bb-db:
    type: b2
    path: 'zee-backup:/databases'
